### ISSUE TITLE
Question: How to read IR values in Quartz Composer OSC Receiver

### ISSUE THREAD

**Issue by phylaxis** [kronihias/DarwiinRemoteOSC#2]
Sorry to post this here, but I wasn't sure how else to reach you. I have successfully run the software and connected to the OSC receiver in Quartz Composer, but I can;t figure out how I can access the OSC arguments passed from DarwiinRemoteOSC. How can I do that?

**Comment by kronihias** [comment]
Hi, can't help you here, I don't use QuartzComposer. Try a Quartz 
Composer list/forum.
Best, Matthias
